GET http://localhost:3000 HTTP/1.1
###
GET http://localhost:3000/categories HTTP/1.1
###
GET http://localhost:3000/categories/1 HTTP/1.1
###
POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "Expediente",
    "description": "Produtos de Expediente..."
}
###
PUT http://localhost:3000/categories/1 HTTP/1.1
content-type: application/json

{
    "name": "Teste",
    "description": "Produtos de Teste..."
}
###
DELETE http://localhost:3000/categories/1 HTTP/1.1
###
GET http://localhost:3000/receivers HTTP/1.1
###
GET http://localhost:3000/receivers/1 HTTP/1.1
###
POST http://localhost:3000/receivers HTTP/1.1
content-type: application/json

{
    "name": "Agricultura"
    # "description": "Tal"
}
###
PUT http://localhost:3000/receivers/3 HTTP/1.1
content-type: application/json

{
    "name": "Agricultura",
    "description": "asdf"
}
###
GET http://localhost:3000/products HTTP/1.1
###
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "categoryId": 1,
    "name": "Caneta azul",
    "quantity": 5
}
###
GET http://localhost:3000/products/1 HTTP/1.1
###
PUT http://localhost:3000/products/1 HTTP/1.1
content-type: application/json

{
    "categoryId": 2,
    "name": "Caneta verde",
    "description": "Descrição",
    "quantity": 7
}
###
DELETE http://localhost:3000/products/2 HTTP/1.1
###
GET http://localhost:3000/transictions HTTP/1.1
###
GET http://localhost:3000/transictions/2 HTTP/1.1
###
POST http://localhost:3000/transictions HTTP/1.1
content-type: application/json

{
    "type": "entry",
    "receiverId": 1,
    "letter": "45",
    "observation": "Deu certo"
}
###
PUT http://localhost:3000/transictions/2 HTTP/1.1
content-type: application/json

{
    "type": "exit",
    "receiverId": 1,
    "letter": "78",
    "observation": "Será que vai?"
}
###
DELETE http://localhost:3000/transictions/3 HTTP/1.1